### ISSUE TITLE
[JOSS REVIEW] Remove artifact files and add a .gitignore file

### ISSUE THREAD

**Issue by jrbourbeau** [ornlpmcp/ASCENDS#2]
There are several files and directories in this repository that are artifacts of some other process. For example, a log file associated with a pip installation (`pip.log`), compiled Python bytecode (`__pycache__`), Jupyter notebook checkpoints (`.ipynb_checkpoints`), etc. In my experience, these types of files are not included alongside the source code for a Python project. 

I recommend adding a [`.gitignore` file](https://git-scm.com/docs/gitignore) to this repository (e.g. GitHub maintains a nice [`.gitignore` for Python projects](https://github.com/github/gitignore/blob/master/Python.gitignore) that could be used here) and removing files in this repository that are already tracked by `git`, but would be ignored based on the entries in the new `.gitignore` file. 

To be clear, this is not required as part of the JOSS review, but is highly recommended. 

xref https://github.com/openjournals/joss-reviews/issues/1656

**Comment by ornlpmcp** [comment]
Thanks for your review! I removed the artifact files you mentioned and added a .gitignore file in the repository.

**Comment by jrbourbeau** [comment]
Great, thank you! `build/` and `dist/` are both mentioned in the `.gitignore` file and can also be removed too (those are Python package distribution artifacts). Is the `output/` directory being used anywhere? If not, I suspect it may be okay to remove that too

**Comment by ornlpmcp** [comment]
They are removed too. Thanks - I am working on other review items. Having an 'output' directory makes it easier for users to test code following the example. Stay tuned thanks a lot.
