### ISSUE TITLE
[JOSS REVIEW] List package dependencies

### ISSUE THREAD

**Issue by jrbourbeau** [ornlpmcp/ASCENDS#4]
The packages required to install and run ASCENDS should be explicitly listed in the `README.md` (e.g. in the "Installation" section).

I see there is this list of packages in `setup.py`:

https://github.com/ornlpmcp/ASCENDS/blob/4f1fd58412048446b904befd6a32c4289b1df9e9/setup.py#L21-L29

Is this list up-to-date? If so, that should be sufficient 

xref https://github.com/openjournals/joss-reviews/issues/1656

**Comment by ornlpmcp** [comment]
Now all dependencies with proper versions are in 'environment.yml'
I updated the installation process to use conda as you guided.
no pip is needed.
Thanks a lot.

**Comment by ornlpmcp** [comment]
I also updated README.md to mention the environment.yml and remove description on pip and pip_requirement.txt and conda_requirement.txt
