### ISSUE TITLE
[JOSS REVIEW] Add tests

### ISSUE THREAD

**Issue by jrbourbeau** [ornlpmcp/ASCENDS#5]
Running the current [`notebook/reference.ipynb`](https://github.com/ornlpmcp/ASCENDS/blob/4f1fd58412048446b904befd6a32c4289b1df9e9/notebook/reference.ipynb) Jupyter notebook requires `ascends` to be installed, but (to my best knowledge) doesn't test any of the actual output of the `ascends` package. So running this notebook does provide a test that `ascends` is installed, but not that any of the output it is providing is correct. 

Could you add some way that I can verify this software is behaving as expected? For example, in `notebook/reference.ipynb`, you're printing lots of numbers. Could you modify things such that those print statements are turned into `assert` statements? So instead of, for example, printing the model performance, you assert that the outputted model performance is equal to some known or expected value?

This is generally very useful to convince both yourself and others that things are working properly and to ensure that future modifications to the code don't unknowingly break the code's behavior. 

xref https://github.com/openjournals/joss-reviews/issues/1656

**Comment by jrbourbeau** [comment]
I also noticed that the data files in `reference.ipynb` (`data/iris.csv` and `data/BostonHousing.csv`) are not included in the repository and running `reference.ipynb` yields `FileNotFoundError` errors unless those `.csv` files are manually downloaded. I recommend either:

- Including instructions on how to download the required data files in the "Jupyter Notebook/API Reference/Testing" section of `README.md`

- Including those data files in the repository as to avoid manual downloading altogether

- Using `scikit-learn`'s [`load_boston`](https://scikit-learn.org/stable/modules/generated/sklearn.datasets.load_boston.html#sklearn.datasets.load_boston) and [`load_iris`](https://scikit-learn.org/stable/modules/generated/sklearn.datasets.load_iris.html#sklearn.datasets.load_iris) utilities to access those two particular datasets, which are included in `scikit-learn`.

**Comment by ornlpmcp** [comment]
@jrbourbeau I modified the notebook/reference.ipynb according to your suggestion
- I included all the dataset in the repository
- now dependencies include jupyter notebook for users convenience of testing
- reference.ipynb now includes asserts so the users can test if everything works correctly.
Thanks for your suggenstions.
