### ISSUE TITLE
[JOSS REVIEW] Consider using conda for installing dependencies

### ISSUE THREAD

**Issue by jrbourbeau** [ornlpmcp/ASCENDS#7]
In the installation instructions you recommend using `conda` for installing dependencies, but then proceed to install most dependencies using `pip`. You might consider creating a `conda` environment file (see https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#create-env-file-manually) to instead install all dependencies using `conda` instead of with `pip`. 

Further, you could even consider adding a package to [conda-forge](https://conda-forge.org/) so that ASCENDS can itself be installed using `conda`. 

To be clear, this is not required as part of the JOSS review, just a recommendation to potentially avoid installation issues that have come up during the review. 

xref https://github.com/openjournals/joss-reviews/issues/1656

**Comment by ornlpmcp** [comment]
I changed the installation process so now pip does not need to be installed. You can simply install all dependencies by creating a dedicated environment using environment.yml in the repository. I will look into conda-forge, but for now I want to keep it simple. Thanks again for your review.

**Comment by jrbourbeau** [comment]
Thanks @ornlpmcp! 

> I will look into conda-forge, but for now I want to keep it simple

Sounds good. That's certainly not required, just thought it was worth mentioning as an option
